name: achievement-collector

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  block_update:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python main.py
        
      - name: execute py script 
        run: python main.py
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            token: ${{ secrets.QUYETLV12_PULL_01 }}
            commit-message: Update progress
            title: Update progress
            branch: update-progress
